In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pprint import pprint
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
import csv
from sklearn.preprocessing import OneHotEncoder

Using TensorFlow backend.


In [2]:
train = pd.read_csv('money_label.csv').values
train=pd.DataFrame(train,columns='img_name img_label'.split())

In [3]:
train_image = []
def img_to_array(number,iteration):
    for i in range(iteration):
        img = image.load_img('bangla-money/Training/'+str(number)+'/'+str(number)+'_'+str(i)+'.jpg', target_size=(120,250,1), color_mode="grayscale")
        img = image.img_to_array(img)
        img = img/255
        train_image.append(img)

In [4]:
img_to_array(1,101)
img_to_array(2,213)
img_to_array(5,213)
img_to_array(10,213)
img_to_array(20,173)
img_to_array(50,213)
img_to_array(100,208)
img_to_array(500,136)
img_to_array(1000,167)

In [5]:
X = np.array(train_image)

In [6]:
category=[1,2,3,4,5,6,7,8,9]
label_encoder=LabelEncoder()
int_encoded=label_encoder.fit_transform(category)
onehot_encoder=OneHotEncoder(sparse=False)
int_encoded= int_encoded.reshape(len(int_encoded),1)
onehot_encoded=onehot_encoder.fit_transform(int_encoded)
print(len(onehot_encoded))

9


C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [7]:
vectorize_label=[]
for i in train['img_label']:
    if i == 1:
        vectorize_label.append(onehot_encoded[0])
    elif i == 2:
        vectorize_label.append(onehot_encoded[1])
    elif i == 5:
        vectorize_label.append(onehot_encoded[2])
    elif i == 10:
        vectorize_label.append(onehot_encoded[3])
    elif i == 20:
        vectorize_label.append(onehot_encoded[4])
    elif i == 50:
        vectorize_label.append(onehot_encoded[5])
    elif i == 100:
        vectorize_label.append(onehot_encoded[6])
    elif i == 500:
        vectorize_label.append(onehot_encoded[7])
    elif i == 1000:
        vectorize_label.append(onehot_encoded[8])

In [8]:
vectorize_label=np.array(vectorize_label)
print(vectorize_label)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [9]:
y=vectorize_label

In [10]:
y.shape

(1637, 9)

In [11]:
test_img=[]
import os
for dirname, _, filenames in os.walk('bangla-money/Testing/'):
    for filename in range(len(filenames)):
        if filenames[filename]=="Thumbs.db":
            print("Its not an Image")
        else:
            img = image.load_img('bangla-money/Testing/'+filenames[filename], target_size=(120,250,1), color_mode="grayscale")
            img = image.img_to_array(img)
            img = img/255
            test_img.append(img)
test_img=np.array(test_img)

Its not an Image


In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=(120,250,1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(256, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(9, activation='softmax'))


In [13]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [14]:
cnn=model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

Train on 1309 samples, validate on 328 samples
Epoch 1/10
1309/1309 [==============================] - 101s 77ms/step - loss: 2.1957 - accuracy: 0.1146 - val_loss: 2.1785 - val_accuracy: 0.1098
Epoch 2/10
1309/1309 [==============================] - 96s 73ms/step - loss: 2.1825 - accuracy: 0.1245 - val_loss: 2.1760 - val_accuracy: 0.1098
Epoch 3/10
1309/1309 [==============================] - 101s 77ms/step - loss: 2.1817 - accuracy: 0.1413 - val_loss: 2.1709 - val_accuracy: 0.1280
Epoch 4/10
1309/1309 [==============================] - 97s 74ms/step - loss: 2.1539 - accuracy: 0.1436 - val_loss: 2.1877 - val_accuracy: 0.1250
Epoch 5/10
1309/1309 [==============================] - 96s 73ms/step - loss: 1.7482 - accuracy: 0.3743 - val_loss: 1.0081 - val_accuracy: 0.7409
Epoch 6/10
1309/1309 [==============================] - 97s 74ms/step - loss: 0.8169 - accuracy: 0.7426 - val_loss: 0.3879 - val_accuracy: 0.8841
Epoch 7/10
1309/1309 [==============================] - 96s 73ms/step - los

In [15]:
p=model.predict(test_img,batch_size=None,verbose=0,steps=None)

In [16]:
# from tensorflow.keras.models import load_model
# model=load_model('CNN_best.hdf5')

In [17]:
# p=model.predict(test_img,batch_size=None,verbose=0,steps=None)

save_csv={}
for i in range(len(p)):
    if p[i].argmax()==0:
        save_csv[i]=1
        print(i,"1")
    elif p[i].argmax()==1:
        save_csv[i]=2
        print(i,"2")
    elif p[i].argmax()==2:
        save_csv[i]=5
        print(i,"5")
    elif p[i].argmax()==3:
        save_csv[i]=10
        print(i,"10")
    elif p[i].argmax()==4:
        save_csv[i]=20
        print(i,"20")
    elif p[i].argmax()==5:
        save_csv[i]=50
        print(i,"50")
    elif p[i].argmax()==6:
        save_csv[i]=100
        print(i,"100")
    elif p[i].argmax()==7:
        save_csv[i]=500
        print(i,"500")
    elif p[i].argmax()==8:
        save_csv[i]=1000
        print(i,"1000")
        
path="bangla-money/Testing"
test_files=[os.path.join(path,f) for f in os.listdir(path) if f.endswith('.jpg')]
sps=[im.replace(path+'\\','') for im in test_files]
y_actual=np.array([ sp[:sp.index('_')] for sp in sps], dtype=int)
print(y_actual)

a=0
for i in range(len(save_csv)):
    if save_csv[i]==y_actual[i]:
        a+=1
b=(float(a)/len(save_csv))*100
print(b)

0 20
1 1000
2 1000
3 100
4 1000
5 1000
6 1000
7 1000
8 1000
9 1000
10 1000
11 1000
12 1000
13 1000
14 1000
15 50
16 1000
17 1000
18 1000
19 100
20 1000
21 1000
22 1000
23 1000
24 1000
25 1000
26 1000
27 1000
28 5
29 1000
30 1000
31 1000
32 1000
33 1000
34 1000
35 20
36 1000
37 1000
38 1000
39 1000
40 100
41 1000
42 1000
43 50
44 1000
45 1000
46 1000
47 100
48 1000
49 1000
50 1000
51 1000
52 100
53 100
54 100
55 100
56 100
57 100
58 100
59 100
60 100
61 100
62 100
63 100
64 100
65 100
66 100
67 100
68 100
69 100
70 100
71 100
72 100
73 50
74 100
75 100
76 100
77 100
78 100
79 100
80 100
81 100
82 100
83 100
84 100
85 100
86 100
87 100
88 100
89 100
90 10
91 10
92 10
93 10
94 10
95 10
96 5
97 10
98 50
99 10
100 10
101 50
102 10
103 50
104 20
105 20
106 10
107 10
108 10
109 10
110 10
111 10
112 10
113 10
114 10
115 10
116 10
117 10
118 5
119 5
120 10
121 10
122 10
123 10
124 10
125 10
126 10
127 1
128 1
129 1
130 1
131 1
132 1
133 1
134 1
135 50
136 1
137 1
138 1
139 1
140 1
141 1
142 1
1

In [17]:
# a=0
# for i in range(len(save_csv)):
#     if save_csv[i]==y_actual[i]:
#         a+=1
# b=(float(a)/len(save_csv))*100
# print(b)

96.996996996997


In [61]:
#model save
# model_name="CNN_"+str(b)+"_.hdf5"
# keras.models.save_model(model, model_name)